on:
  push:
    branches:
      - main
      - master
  schedule:
  - cron: "0 6 * * 4"
  repository_dispatch:
    types: [update]

name: update-data

jobs:
  render:
    name: update-data
    runs-on: ubuntu-18.04
    env:
      GITHUB_PAT: ${{ secrets.PAT }}
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          options(renv.config.repos.override = c(pkgmanager = "https://packagemanager.rstudio.com/all/__linux__/bionic/2022-01-03+Y3JhbiwyOjQ1MjYyMTU7NTY4Qjk1ODA", cran = "https://cloud.r-project.org"))
          renv::restore()
      - name: Install remotes, and the local package
        env:
          GITHUB_PAT: ${{ secrets.PAT }}
        run: |
          options(repos = c(pkgmanager = "https://packagemanager.rstudio.com/all/__linux__/bionic/2022-01-03+Y3JhbiwyOjQ1MjYyMTU7NTY4Qjk1ODA"))
          if (!requireNamespace("remotes", quietly = TRUE)) install.packages("remotes")
          remotes::install_local(".", force = TRUE)
        shell: Rscript {0}
      - name: Execute Script
        run: |
          Rscript "data-raw/update.R"
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data-raw/dados_SRAG.RDS
          git commit -m 'Update data' || echo "Update data"
          git push origin || echo "Update data"
